{
nixConfig = {
    extra-substituters = [
	"https://hyprland.cachix.org/"
	"https://cache.nixos.org/"
	"https://cachix.cachix.org/"
	"https://nix-community.cachix.org/"
    ];
    extra-trusted-public-keys = [
        "hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc="
	      "cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM="
	      "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
	      "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
    ];
  };

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/master";
    envycontrol.url = "github:bayasdev/envycontrol";
    hyprland.url = "github:hyprwm/Hyprland";
    flake-utils.url = "github:numtide/flake-utils";
    rust-overlay.url = "github:oxalica/rust-overlay";
    systems.url = "github:nix-systems/x86_64-linux";
    flake-utils.inputs.systems.follows = "systems";
  };

 outputs = { 
    self,
    nixpkgs,
    rust-overlay,
    flake-utils,
    ...   
      }@inputs: let
        overlays = [ (import rust-overlay) ];
        system = "x86_64-linux";
        pkgs = import nixpkgs {
          inherit system overlays;
        };
        in
{
      system = "x86_64-linux";
      devShells.default =
          with pkgs;
          mkShell rec {
            buildInputs = [
			libwayland-client
            pkg-config
            rust-bin.nightly.latest.default
            libarchive
            openssl
            steamcmd
			spotifyd
			spotify-tray
			nvtopPackages.full
			xorg.libXi
			spotify-player
			librespot
			lxappearance
			kdePackages.kwin
      		kdePackages.kwin-x11
      		libsForQt5.kwindowsystem
      		kdePackages.kwindowsystem
      		gamescope
      		bubblewrap
      		goldberg-emu
			libx11
			xorg_sys_opengl
			SDL
			sdl3
			SDL2
			libGL
			libxkbcommon
			libarchive
			openssl
			qbittorrent-nox
			libadwaita
			gtk4
			elegant-sddm
			gtk3-x11
			bumblebee
			nvidia-modprobe
			libgtkflow4
			libgtkflow3
			yt-dlp
			nvidia_oc
			discord-rpc
			vencord
			vencord-web-extension
			webcord-vencord
			direnv
			bc
			cairo
			pixman
			discord-canary
			dotnet-sdk_9 
			betterdiscordctl
			betterdiscord-installer
			discord-gamesdk
			lxappearance-gtk2
			pango
			libthai
			harfbuzz
			adwaita-qt6
			adwaita-icon-theme
			#inputs.envycontrol.packages.x86_64-linux.default
			cachix
			xsettingsd
			xorg.xrdb
			wlr-protocols
			lm_sensors
			libusbp
			libusb1
			xorg.xhost
			google-chrome
			librewolf-bin
			unrar-wrapper
			unrar
			unar
			unrar-free
			adwaita-icon-theme
			gnomeExtensions.appindicator
			gnome-settings-daemon
			gh
			coolercontrol.coolercontrol-gui
			coolercontrol.coolercontrold
			coolercontrol.coolercontrol-ui-data
			coolercontrol.coolercontrol-liqctld
			intel-media-driver 
			vaapiIntel        
			vaapiVdpau
			intel-gmmlib
			vaapi-intel-hybrid
			nodejs_22
			libva
			qt6.qtsvg
			libdrm
			egl-wayland
			libnvidia-container
			libvdpau-va-gl
			libvdpau
			virtualglLib
			intel-compute-runtime
			intel-compute-runtime
			nv-codec-headers-12
			intel-ocl
			ffmpeg-full
			nvidia-vaapi-driver
			vulkan-extension-layer
			spirv-tools
			vulkan-utility-libraries
			mesa
			libdrm
			xorg.xf86videonv
			xorg.xf86inputevdev
			xorg.xf86inputlibinput
			intel-vaapi-driver
			spotify
			zsh
			meson
			ninja
			jq
			lshw
			gparted
			gnome-disk-utility
			hyprcursor
			vim
			prismlauncher
			openal
			mlx42
			glfw
			glfw3-minecraft
			qt6.qtwayland
			protonup-qt
			lutris	
			ncspot
			librespot
			gamemode
			goverlay
			vscode.fhs
			gnumake
			gitFull
			baobab
			gimp
			gnome-text-editor
			pavucontrol
			yad
			unzip
			wget
			xdotool
			kdePackages.kdenlive
			protontricks
			winetricks
			wineWowPackages.waylandFull
			file-roller
			xorg.xwininfo
			alacritty
			wofi
			wl-clipboard
			btop
			helvum
			grim
			grimblast
			mpv
			audacity
			stacer
			libva
			virtualglLib
			libvdpau-va-gl
			vulkan-extension-layer
			vulkan-utility-libraries
			mesa
			glfw
			glfw3-minecraft
			xorg.xf86inputevdev
			xorg.xf86inputlibinput
			libnvidia-container
			intel-compute-runtime
			vaapiVdpau
			libxcursor
			vaapiIntel
			intel-media-driver
			nvidia-vaapi-driver
			xorg.xf86videonv
			intel-vaapi-driver
			nv-codec-headers-12
			ffmpeg-full
			config.boot.kernelPackages.nvidia_x11_beta
			config.boot.kernelPackages.nvidia_x11_beta_open
			libnvidia-container
			nvidia-vaapi-driver
			nvidia-vaapi-driver
			nvidia-docker
			nvidia_cg_toolkit
			nvidia-texture-tools
			nvidia-optical-flow-sdk
			pciutils
			zsh-syntax-highlighting
			fastfetch
			slurp
			util-linux
			wl-clipboard
			polkit_gnome
			polkit
			jdk23
			libglvnd
			glew
			hyprlock
			hypridle
			eglexternalplatform
			egl-wayland
			mangohud
			pkgsi686Linux.mangohud
			curl
			glibc
			xorg.xf86videonv
			chiaki-ng
			intel-vaapi-driver
			libnvidia-container
			glib
			virtualglLib
			glibmm
			libglibutil
			glibcInfo
			glibc_multi
			glibcLocales
			libdrm
			mesa
			glibc_memusage
			glibcLocalesUtf8
			liquidctl
			iconv
			libiconv
			gfortran
			gdb
			polkit_gnome
			libva-utils
			nvidia-vaapi-driver
			nvidia-docker
			nvidia_cg_toolkit
			nvidia-texture-tools
			nvidia-optical-flow-sdk
			nv-codec-headers-12
			xdg-utils
			xdg-desktop-portal
			inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.hyprland
			inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.xdg-desktop-portal-hyprland
			nautilus
			libcdada
			vulkan-tools
			libva
			virtualglLib
			libvdpau-va-gl
			vulkan-extension-layer
			vulkan-utility-libraries
			mesa
			glfw
			glfw3-minecraft
			xorg.xf86inputevdev
			xorg.xf86inputlibinput
			libnvidia-container
			intel-compute-runtime
			vaapiVdpau
			libxcursor
			vaapiIntel
			intel-media-driver
			nvidia-vaapi-driver
			xorg.xf86videonv
			intel-vaapi-driver
			nv-codec-headers-12
			ffmpeg-full
			config.boot.kernelPackages.nvidia_x11_beta
			config.boot.kernelPackages.nvidia_x11_beta_open
			libnvidia-container
			nvidia-vaapi-driver
			nvidia-vaapi-driver
			nvidia-docker
			nvidia_cg_toolkit
			nvidia-texture-tools
			nvidia-optical-flow-sdk
			ffmpeg-full
			onlyoffice-bin
			wineWowPackages.stable
			winetricks
			waybar
			mako
			vulkan-tools
			vulkan-loader
			vulkan-headers
			vulkan-tools-lunarg
			vulkan-extension-layer
			vulkan-utility-libraries
			libva
			virtualglLib
			libvdpau-va-gl
			vulkan-extension-layer
			vulkan-utility-libraries
			mesa
			glfw
			glfw3-minecraft
			xorg.xf86inputevdev
			xorg.xf86inputlibinput
			libnvidia-container
			intel-compute-runtime
			vaapiVdpau
			libxcursor
			vaapiIntel
			intel-media-driver
			nvidia-vaapi-driver
			xorg.xf86videonv
			intel-vaapi-driver
			nv-codec-headers-12
			ffmpeg-full
			config.boot.kernelPackages.nvidia_x11_beta
			config.boot.kernelPackages.nvidia_x11_beta_open
			libnvidia-container
			nvidia-vaapi-driver
			nvidia-vaapi-driver
			nvidia-docker
			nvidia_cg_toolkit
			nvidia-texture-tools
			nvidia-optical-flow-sdk
            sdl2-compat
            xorg.libX11
            libx11
            rust-bin.nightly.latest.default
            xorg.libX11
            glfw-wayland
            xorg.libXcursor
            libxcursor
            xorg.libXrandr
            xorg.libXi
            xorg.libxcb
            libxkbcommon
            vulkan-loader
            wayland
            kdePackages.kwin
            kdePackages.kwin-x11
            libsForQt5.kwindowsystem
            kdePackages.kwindowsystem
            gamescope
            bubblewrap
            goldberg-emu
              xorg.libXcursor
              xorg.libXrandr
              xorg.libXi
              xorg.libxcb
              libxkbcommon
              vulkan-loader
              wayland
            ];
            runtimeDependencies = [
			libwayland-client
            wayland
            libGL
            libx11
            glfw-wayland
            steamcmd
			spotifyd
			spotify-tray
			nvtopPackages.full
			xorg.libXi
			spotify-player
			librespot
			lxappearance
			kdePackages.kwin
      kdePackages.kwin-x11
      libsForQt5.kwindowsystem
      kdePackages.kwindowsystem
      gamescope
      bubblewrap
      goldberg-emu
			libx11
			xorg_sys_opengl
			SDL
			sdl3
			SDL2
			libGL
			libxkbcommon
			libarchive
			openssl
			qbittorrent-nox
			libadwaita
			gtk4
			elegant-sddm
			gtk3-x11
			bumblebee
			nvidia-modprobe
			libgtkflow4
			libgtkflow3
			yt-dlp
			nvidia_oc
			discord-rpc
			vencord
			vencord-web-extension
			webcord-vencord
			direnv
			bc
			cairo
			pixman
			discord-canary
			dotnet-sdk_9 
			betterdiscordctl
			betterdiscord-installer
			discord-gamesdk
			lxappearance-gtk2
			pango
			libthai
			harfbuzz
			adwaita-qt6
			adwaita-icon-theme
			#inputs.envycontrol.packages.x86_64-linux.default
			cachix
			xsettingsd
			xorg.xrdb
			wlr-protocols
			lm_sensors
			libusbp
			libusb1
			xorg.xhost
			google-chrome
			librewolf-bin
			unrar-wrapper
			unrar
			unar
			unrar-free
			adwaita-icon-theme
			gnomeExtensions.appindicator
			gnome-settings-daemon
			gh
			coolercontrol.coolercontrol-gui
			coolercontrol.coolercontrold
			coolercontrol.coolercontrol-ui-data
			coolercontrol.coolercontrol-liqctld
			intel-media-driver 
			vaapiIntel        
			vaapiVdpau
			intel-gmmlib
			vaapi-intel-hybrid
			nodejs_22
			libva
			qt6.qtsvg
			libdrm
			egl-wayland
			libnvidia-container
			libvdpau-va-gl
			libvdpau
			virtualglLib
			intel-compute-runtime
			intel-compute-runtime
			nv-codec-headers-12
			intel-ocl
			ffmpeg-full
			nvidia-vaapi-driver
			vulkan-extension-layer
			spirv-tools
			vulkan-utility-libraries
			mesa
			libdrm
			xorg.xf86videonv
			xorg.xf86inputevdev
			xorg.xf86inputlibinput
			intel-vaapi-driver
			spotify
			zsh
			meson
			ninja
			jq
			lshw
			gparted
			gnome-disk-utility
			hyprcursor
			vim
			prismlauncher
			openal
			mlx42
			glfw
			glfw3-minecraft
			qt6.qtwayland
			protonup-qt
			lutris	
			ncspot
			librespot
			gamemode
			goverlay
			vscode.fhs
			gnumake
			gitFull
			baobab
			gimp
			gnome-text-editor
			pavucontrol
			yad
			unzip
			wget
			xdotool
			kdePackages.kdenlive
			protontricks
			winetricks
			wineWowPackages.waylandFull
			file-roller
			xorg.xwininfo
			alacritty
			wofi
			wl-clipboard
			btop
			helvum
			grim
			grimblast
			mpv
			audacity
			stacer
			libva
			virtualglLib
			libvdpau-va-gl
			vulkan-extension-layer
			vulkan-utility-libraries
			mesa
			glfw
			glfw3-minecraft
			xorg.xf86inputevdev
			xorg.xf86inputlibinput
			libnvidia-container
			intel-compute-runtime
			vaapiVdpau
			libxcursor
			vaapiIntel
			intel-media-driver
			nvidia-vaapi-driver
			xorg.xf86videonv
			intel-vaapi-driver
			nv-codec-headers-12
			ffmpeg-full
			config.boot.kernelPackages.nvidia_x11_beta
			config.boot.kernelPackages.nvidia_x11_beta_open
			libnvidia-container
			nvidia-vaapi-driver
			nvidia-vaapi-driver
			nvidia-docker
			nvidia_cg_toolkit
			nvidia-texture-tools
			nvidia-optical-flow-sdk
			pciutils
			zsh-syntax-highlighting
			fastfetch
			slurp
			util-linux
			wl-clipboard
			polkit_gnome
			polkit
			jdk23
			libglvnd
			glew
			hyprlock
			hypridle
			eglexternalplatform
			egl-wayland
			mangohud
			pkgsi686Linux.mangohud
			curl
			glibc
			xorg.xf86videonv
			chiaki-ng
			intel-vaapi-driver
			libnvidia-container
			glib
			virtualglLib
			glibmm
			libglibutil
			glibcInfo
			glibc_multi
			glibcLocales
			libdrm
			mesa
			glibc_memusage
			glibcLocalesUtf8
			liquidctl
			iconv
			libiconv
			gfortran
			gdb
			polkit_gnome
			libva-utils
			nvidia-vaapi-driver
			nvidia-docker
			nvidia_cg_toolkit
			nvidia-texture-tools
			nvidia-optical-flow-sdk
			nv-codec-headers-12
			xdg-utils
			xdg-desktop-portal
			inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.hyprland
			inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.xdg-desktop-portal-hyprland
			nautilus
			libcdada
			vulkan-tools
			libva
			virtualglLib
			libvdpau-va-gl
			vulkan-extension-layer
			vulkan-utility-libraries
			mesa
			glfw
			glfw3-minecraft
			xorg.xf86inputevdev
			xorg.xf86inputlibinput
			libnvidia-container
			intel-compute-runtime
			vaapiVdpau
			libxcursor
			vaapiIntel
			intel-media-driver
			nvidia-vaapi-driver
			xorg.xf86videonv
			intel-vaapi-driver
			nv-codec-headers-12
			ffmpeg-full
			config.boot.kernelPackages.nvidia_x11_beta
			config.boot.kernelPackages.nvidia_x11_beta_open
			libnvidia-container
			nvidia-vaapi-driver
			nvidia-vaapi-driver
			nvidia-docker
			nvidia_cg_toolkit
			nvidia-texture-tools
			nvidia-optical-flow-sdk
			ffmpeg-full
			onlyoffice-bin
			wineWowPackages.stable
			winetricks
			waybar
			mako
			vulkan-tools
			vulkan-loader
			vulkan-headers
			vulkan-tools-lunarg
			vulkan-extension-layer
			vulkan-utility-libraries
			libva
			virtualglLib
			libvdpau-va-gl
			vulkan-extension-layer
			vulkan-utility-libraries
			mesa
			glfw
			glfw3-minecraft
			xorg.xf86inputevdev
			xorg.xf86inputlibinput
			libnvidia-container
			intel-compute-runtime
			vaapiVdpau
			libxcursor
			vaapiIntel
			intel-media-driver
			nvidia-vaapi-driver
			xorg.xf86videonv
			intel-vaapi-driver
			nv-codec-headers-12
			ffmpeg-full
			config.boot.kernelPackages.nvidia_x11_beta
			config.boot.kernelPackages.nvidia_x11_beta_open
			libnvidia-container
			nvidia-vaapi-driver
			nvidia-vaapi-driver
			nvidia-docker
			nvidia_cg_toolkit
			nvidia-texture-tools
			nvidia-optical-flow-sdk
            kdePackages.kwin
              kdePackages.kwin-x11
              libsForQt5.kwindowsystem
              kdePackages.kwindowsystem
              gamescope
              bubblewrap
              goldberg-emu
            libxkbcommon
            ];

            LD_LIBRARY_PATH = "${pkgs.lib.makeLibraryPath (with pkgs; [
				wayland
							libwayland-client
            wayland
            libGL
            libx11
            glfw-wayland
            steamcmd
			spotifyd
			spotify-tray
			nvtopPackages.full
			xorg.libXi
			spotify-player
			librespot
			lxappearance
			kdePackages.kwin
      kdePackages.kwin-x11
      libsForQt5.kwindowsystem
      kdePackages.kwindowsystem
      gamescope
      bubblewrap
      goldberg-emu
			libx11
			xorg_sys_opengl
			SDL
			sdl3
			SDL2
			libGL
			libxkbcommon
			libarchive
			openssl
			qbittorrent-nox
			libadwaita
			gtk4
			elegant-sddm
			gtk3-x11
			bumblebee
			nvidia-modprobe
			libgtkflow4
			libgtkflow3
			yt-dlp
			nvidia_oc
			discord-rpc
			vencord
			vencord-web-extension
			webcord-vencord
			direnv
			bc
			cairo
			pixman
			discord-canary
			dotnet-sdk_9 
			betterdiscordctl
			betterdiscord-installer
			discord-gamesdk
			lxappearance-gtk2
			pango
			libthai
			harfbuzz
			adwaita-qt6
			adwaita-icon-theme
			#inputs.envycontrol.packages.x86_64-linux.default
			cachix
			xsettingsd
			xorg.xrdb
			wlr-protocols
			lm_sensors
			libusbp
			libusb1
			xorg.xhost
			google-chrome
			librewolf-bin
			unrar-wrapper
			unrar
			unar
			unrar-free
			adwaita-icon-theme
			gnomeExtensions.appindicator
			gnome-settings-daemon
			gh
			coolercontrol.coolercontrol-gui
			coolercontrol.coolercontrold
			coolercontrol.coolercontrol-ui-data
			coolercontrol.coolercontrol-liqctld
			intel-media-driver 
			vaapiIntel        
			vaapiVdpau
			intel-gmmlib
			vaapi-intel-hybrid
			nodejs_22
			libva
			qt6.qtsvg
			libdrm
			egl-wayland
			libnvidia-container
			libvdpau-va-gl
			libvdpau
			virtualglLib
			intel-compute-runtime
			intel-compute-runtime
			nv-codec-headers-12
			intel-ocl
			ffmpeg-full
			nvidia-vaapi-driver
			vulkan-extension-layer
			spirv-tools
			vulkan-utility-libraries
			mesa
			libdrm
			xorg.xf86videonv
			xorg.xf86inputevdev
			xorg.xf86inputlibinput
			intel-vaapi-driver
			spotify
			zsh
			meson
			ninja
			jq
			lshw
			gparted
			gnome-disk-utility
			hyprcursor
			vim
			prismlauncher
			openal
			mlx42
			glfw
			glfw3-minecraft
			qt6.qtwayland
			protonup-qt
			lutris	
			ncspot
			librespot
			gamemode
			goverlay
			vscode.fhs
			gnumake
			gitFull
			baobab
			gimp
			gnome-text-editor
			pavucontrol
			yad
			unzip
			wget
			xdotool
			kdePackages.kdenlive
			protontricks
			winetricks
			wineWowPackages.waylandFull
			file-roller
			xorg.xwininfo
			alacritty
			wofi
			wl-clipboard
			btop
			helvum
			grim
			grimblast
			mpv
			audacity
			stacer
			libva
			virtualglLib
			libvdpau-va-gl
			vulkan-extension-layer
			vulkan-utility-libraries
			mesa
			glfw
			glfw3-minecraft
			xorg.xf86inputevdev
			xorg.xf86inputlibinput
			libnvidia-container
			intel-compute-runtime
			vaapiVdpau
			libxcursor
			vaapiIntel
			intel-media-driver
			nvidia-vaapi-driver
			xorg.xf86videonv
			intel-vaapi-driver
			nv-codec-headers-12
			ffmpeg-full
			config.boot.kernelPackages.nvidia_x11_beta
			config.boot.kernelPackages.nvidia_x11_beta_open
			libnvidia-container
			nvidia-vaapi-driver
			nvidia-vaapi-driver
			nvidia-docker
			nvidia_cg_toolkit
			nvidia-texture-tools
			nvidia-optical-flow-sdk
			pciutils
			zsh-syntax-highlighting
			fastfetch
			slurp
			util-linux
			wl-clipboard
			polkit_gnome
			polkit
			jdk23
			libglvnd
			glew
			hyprlock
			hypridle
			eglexternalplatform
			egl-wayland
			mangohud
			pkgsi686Linux.mangohud
			curl
			glibc
			xorg.xf86videonv
			chiaki-ng
			intel-vaapi-driver
			libnvidia-container
			glib
			virtualglLib
			glibmm
			libglibutil
			glibcInfo
			glibc_multi
			glibcLocales
			libdrm
			mesa
			glibc_memusage
			glibcLocalesUtf8
			liquidctl
			iconv
			libiconv
			gfortran
			gdb
			polkit_gnome
			libva-utils
			nvidia-vaapi-driver
			nvidia-docker
			nvidia_cg_toolkit
			nvidia-texture-tools
			nvidia-optical-flow-sdk
			nv-codec-headers-12
			xdg-utils
			xdg-desktop-portal
			inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.hyprland
			inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.xdg-desktop-portal-hyprland
			nautilus
			libcdada
			vulkan-tools
			libva
			virtualglLib
			libvdpau-va-gl
			vulkan-extension-layer
			vulkan-utility-libraries
			mesa
			glfw
			glfw3-minecraft
			xorg.xf86inputevdev
			xorg.xf86inputlibinput
			libnvidia-container
			intel-compute-runtime
			vaapiVdpau
			libxcursor
			vaapiIntel
			intel-media-driver
			nvidia-vaapi-driver
			xorg.xf86videonv
			intel-vaapi-driver
			nv-codec-headers-12
			ffmpeg-full
			config.boot.kernelPackages.nvidia_x11_beta
			config.boot.kernelPackages.nvidia_x11_beta_open
			libnvidia-container
			nvidia-vaapi-driver
			nvidia-vaapi-driver
			nvidia-docker
			nvidia_cg_toolkit
			nvidia-texture-tools
			nvidia-optical-flow-sdk
			ffmpeg-full
			onlyoffice-bin
			wineWowPackages.stable
			winetricks
			waybar
			mako
			vulkan-tools
			vulkan-loader
			vulkan-headers
			vulkan-tools-lunarg
			vulkan-extension-layer
			vulkan-utility-libraries
			libva
			virtualglLib
			libvdpau-va-gl
			vulkan-extension-layer
			vulkan-utility-libraries
			mesa
			glfw
			glfw3-minecraft
			xorg.xf86inputevdev
			xorg.xf86inputlibinput
			libnvidia-container
			intel-compute-runtime
			vaapiVdpau
			libxcursor
			vaapiIntel
			intel-media-driver
			nvidia-vaapi-driver
			xorg.xf86videonv
			intel-vaapi-driver
			nv-codec-headers-12
			ffmpeg-full
			config.boot.kernelPackages.nvidia_x11_beta
			config.boot.kernelPackages.nvidia_x11_beta_open
			libnvidia-container
			nvidia-vaapi-driver
			nvidia-vaapi-driver
			nvidia-docker
			nvidia_cg_toolkit
			nvidia-texture-tools
			nvidia-optical-flow-sdk
            kdePackages.kwin
              kdePackages.kwin-x11
              libsForQt5.kwindowsystem
              kdePackages.kwindowsystem
              gamescope
              bubblewrap
              goldberg-emu
            libxkbcommon
  ])}:$LD_LIBRARY_PATH";
  shellHook = ''
          export LD_LIBRARY_PATH=${(with pkgs; [
			wayland
						libwayland-client
            wayland
            libGL
            libx11
            glfw-wayland
            steamcmd
			spotifyd
			spotify-tray
			nvtopPackages.full
			xorg.libXi
			spotify-player
			librespot
			lxappearance
			kdePackages.kwin
      kdePackages.kwin-x11
      libsForQt5.kwindowsystem
      kdePackages.kwindowsystem
      gamescope
      bubblewrap
      goldberg-emu
			libx11
			xorg_sys_opengl
			SDL
			sdl3
			SDL2
			libGL
			libxkbcommon
			libarchive
			openssl
			qbittorrent-nox
			libadwaita
			gtk4
			elegant-sddm
			gtk3-x11
			bumblebee
			nvidia-modprobe
			libgtkflow4
			libgtkflow3
			yt-dlp
			nvidia_oc
			discord-rpc
			vencord
			vencord-web-extension
			webcord-vencord
			direnv
			bc
			cairo
			pixman
			discord-canary
			dotnet-sdk_9 
			betterdiscordctl
			betterdiscord-installer
			discord-gamesdk
			lxappearance-gtk2
			pango
			libthai
			harfbuzz
			adwaita-qt6
			adwaita-icon-theme
			#inputs.envycontrol.packages.x86_64-linux.default
			cachix
			xsettingsd
			xorg.xrdb
			wlr-protocols
			lm_sensors
			libusbp
			libusb1
			xorg.xhost
			google-chrome
			librewolf-bin
			unrar-wrapper
			unrar
			unar
			unrar-free
			adwaita-icon-theme
			gnomeExtensions.appindicator
			gnome-settings-daemon
			gh
			coolercontrol.coolercontrol-gui
			coolercontrol.coolercontrold
			coolercontrol.coolercontrol-ui-data
			coolercontrol.coolercontrol-liqctld
			intel-media-driver 
			vaapiIntel        
			vaapiVdpau
			intel-gmmlib
			vaapi-intel-hybrid
			nodejs_22
			libva
			qt6.qtsvg
			libdrm
			egl-wayland
			libnvidia-container
			libvdpau-va-gl
			libvdpau
			virtualglLib
			intel-compute-runtime
			intel-compute-runtime
			nv-codec-headers-12
			intel-ocl
			ffmpeg-full
			nvidia-vaapi-driver
			vulkan-extension-layer
			spirv-tools
			vulkan-utility-libraries
			mesa
			libdrm
			xorg.xf86videonv
			xorg.xf86inputevdev
			xorg.xf86inputlibinput
			intel-vaapi-driver
			spotify
			zsh
			meson
			ninja
			jq
			lshw
			gparted
			gnome-disk-utility
			hyprcursor
			vim
			prismlauncher
			openal
			mlx42
			glfw
			glfw3-minecraft
			qt6.qtwayland
			protonup-qt
			lutris	
			ncspot
			librespot
			gamemode
			goverlay
			vscode.fhs
			gnumake
			gitFull
			baobab
			gimp
			gnome-text-editor
			pavucontrol
			yad
			unzip
			wget
			xdotool
			kdePackages.kdenlive
			protontricks
			winetricks
			wineWowPackages.waylandFull
			file-roller
			xorg.xwininfo
			alacritty
			wofi
			wl-clipboard
			btop
			helvum
			grim
			grimblast
			mpv
			audacity
			stacer
			libva
			virtualglLib
			libvdpau-va-gl
			vulkan-extension-layer
			vulkan-utility-libraries
			mesa
			glfw
			glfw3-minecraft
			xorg.xf86inputevdev
			xorg.xf86inputlibinput
			libnvidia-container
			intel-compute-runtime
			vaapiVdpau
			libxcursor
			vaapiIntel
			intel-media-driver
			nvidia-vaapi-driver
			xorg.xf86videonv
			intel-vaapi-driver
			nv-codec-headers-12
			ffmpeg-full
			config.boot.kernelPackages.nvidia_x11_beta
			config.boot.kernelPackages.nvidia_x11_beta_open
			libnvidia-container
			nvidia-vaapi-driver
			nvidia-vaapi-driver
			nvidia-docker
			nvidia_cg_toolkit
			nvidia-texture-tools
			nvidia-optical-flow-sdk
			pciutils
			zsh-syntax-highlighting
			fastfetch
			slurp
			util-linux
			wl-clipboard
			polkit_gnome
			polkit
			jdk23
			libglvnd
			glew
			hyprlock
			hypridle
			eglexternalplatform
			egl-wayland
			mangohud
			pkgsi686Linux.mangohud
			curl
			glibc
			xorg.xf86videonv
			chiaki-ng
			intel-vaapi-driver
			libnvidia-container
			glib
			virtualglLib
			glibmm
			libglibutil
			glibcInfo
			glibc_multi
			glibcLocales
			libdrm
			mesa
			glibc_memusage
			glibcLocalesUtf8
			liquidctl
			iconv
			libiconv
			gfortran
			gdb
			polkit_gnome
			libva-utils
			nvidia-vaapi-driver
			nvidia-docker
			nvidia_cg_toolkit
			nvidia-texture-tools
			nvidia-optical-flow-sdk
			nv-codec-headers-12
			xdg-utils
			xdg-desktop-portal
			inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.hyprland
			inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.xdg-desktop-portal-hyprland
			nautilus
			libcdada
			vulkan-tools
			libva
			virtualglLib
			libvdpau-va-gl
			vulkan-extension-layer
			vulkan-utility-libraries
			mesa
			glfw
			glfw3-minecraft
			xorg.xf86inputevdev
			xorg.xf86inputlibinput
			libnvidia-container
			intel-compute-runtime
			vaapiVdpau
			libxcursor
			vaapiIntel
			intel-media-driver
			nvidia-vaapi-driver
			xorg.xf86videonv
			intel-vaapi-driver
			nv-codec-headers-12
			ffmpeg-full
			config.boot.kernelPackages.nvidia_x11_beta
			config.boot.kernelPackages.nvidia_x11_beta_open
			libnvidia-container
			nvidia-vaapi-driver
			nvidia-vaapi-driver
			nvidia-docker
			nvidia_cg_toolkit
			nvidia-texture-tools
			nvidia-optical-flow-sdk
			ffmpeg-full
			onlyoffice-bin
			wineWowPackages.stable
			winetricks
			waybar
			mako
			vulkan-tools
			vulkan-loader
			vulkan-headers
			vulkan-tools-lunarg
			vulkan-extension-layer
			vulkan-utility-libraries
			libva
			virtualglLib
			libvdpau-va-gl
			vulkan-extension-layer
			vulkan-utility-libraries
			mesa
			glfw
			glfw3-minecraft
			xorg.xf86inputevdev
			xorg.xf86inputlibinput
			libnvidia-container
			intel-compute-runtime
			vaapiVdpau
			libxcursor
			vaapiIntel
			intel-media-driver
			nvidia-vaapi-driver
			xorg.xf86videonv
			intel-vaapi-driver
			nv-codec-headers-12
			ffmpeg-full
			config.boot.kernelPackages.nvidia_x11_beta
			config.boot.kernelPackages.nvidia_x11_beta_open
			libnvidia-container
			nvidia-vaapi-driver
			nvidia-vaapi-driver
			nvidia-docker
			nvidia_cg_toolkit
			nvidia-texture-tools
			nvidia-optical-flow-sdk
            kdePackages.kwin
              kdePackages.kwin-x11
              libsForQt5.kwindowsystem
              kdePackages.kwindowsystem
              gamescope
              bubblewrap
              goldberg-emu
            libxkbcommon
			])}/lib:$LD_LIBRARY_PATH
          '';

          };

      pkgs = import nixpkgs {
        config.allowUnfree = true;
      };

    # Please replace my-nixos with your hostname
    nixosConfigurations.nixos = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      
      

      # Set all inputs parameters as special arguments for all submodules,
      # so you can directly use all dependencies in inputs in submodules
      specialArgs = { inherit inputs; };
      modules = [
	 {
          nix.settings = {
            substituters = [
              "https://hyprland.cachix.org/"
		          "https://cache.nixos.org/"
		          "https://cachix.cachix.org/"
		          "https://nix-community.cachix.org/"
            ];
            trusted-public-keys = [
              "hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc="
		          "cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM="
		          "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
		          "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
            ];
          };
        }	

        # Import the previous configuration.nix we used,
        # so the old configuration file still takes effect
        ./configuration.nix
	      ./hardware-configuration.nix
	      ./cachix.nix
      ];
    };
  };
}
