# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3759fdef-d2cb-40d1-8569-42e41d083814";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-6413f3fe-b08f-4ef7-a502-2331d530d7c1".device = "/dev/disk/by-uuid/6413f3fe-b08f-4ef7-a502-2331d530d7c1";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0F11-1410";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/d9502c91-3386-4c7e-938a-5cb4b8885750";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-ad091587-982b-4a2a-9613-800a9b0487e6".device = "/dev/disk/by-uuid/ad091587-982b-4a2a-9613-800a9b0487e6";

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
