# shellcheck shell=bash
# Configuration assignments are generated by Nix.
# shellcheck disable=SC2154
set -euo pipefail
role=${1:?activation check role required}
fail() { echo "Activation safety ($role): $*" >&2; exit 1; }

require_mount() {
  local target=$1 expected=$2 fs=$3 fsroot=${4:-}
  local source actual_fs actual_root options
  source=$(findmnt -rn -M "$target" -o SOURCE) || fail "$target is not a mountpoint"
  actual_fs=$(findmnt -rn -M "$target" -o FSTYPE) || fail "cannot inspect $target filesystem"
  [[ "$actual_fs" == "$fs" ]] || fail "$target has unexpected filesystem"
  source=${source%%\[*}
  source=$(realpath -e "$source") || fail "cannot resolve $target device"
  expected=$(realpath -e "$expected") || fail "cannot resolve expected $target device"
  [[ "$source" == "$expected" ]] || fail "$target is on the wrong device"
  options=$(findmnt -rn -M "$target" -o OPTIONS) || fail "cannot inspect $target mount options"
  [[ ",$options," != *,ro,* ]] || fail "$target is read-only"
  if [[ -n "$fsroot" ]]; then
    actual_root=$(findmnt -rn -M "$target" -o FSROOT) || fail "cannot inspect $target subvolume"
    [[ "$actual_root" == "/$fsroot" ]] || fail "$target has unexpected subvolume"
  fi
}

case "$role" in
  persistence)
    require_mount /persist "$expected_device" btrfs "$persist_name"
    ;;
  credentials)
    [[ ! -L "$secret_file" && -f "$secret_file" && -s "$secret_file" && -r "$secret_file" ]] || fail "password hash must be a readable nonempty regular file without aliases"
    [[ "$(stat -c %u "$secret_file")" == 0 && "$(stat -c %h "$secret_file")" == 1 ]] || fail "password hash must be root-owned with one link"
    [[ "$(stat -c %a "$secret_file")" == 600 ]] || fail "password hash must have mode 0600"
    ;;
  esp)
    require_mount /boot "$expected_boot_device" vfat
    available=$(df -B1 --output=avail /boot | tail -n 1 | tr -d ' ')
    [[ "$available" =~ ^[0-9]+$ ]] || fail "cannot measure ESP free space"
    (( available >= esp_reserve )) || fail "ESP free space is below the configured reserve"
    ;;
  topology)
    require_mount / "$expected_device" btrfs "$root_name"
    top=$(mktemp -d "${TMPDIR:-/run}/nixos-activation-topology.XXXXXX")
    cleanup() {
      if mountpoint -q "$top"; then umount "$top" || return 1; fi
      rmdir "$top"
    }
    trap cleanup EXIT
    mount -t btrfs -o ro,subvolid=5 "$expected_device" "$top" || fail "cannot inspect Btrfs top-level read-only"
    for name in "$root_name" "$persist_name"; do
      if [[ -L "$top/$name" ]] || ! btrfs subvolume show "$top/$name" >/dev/null; then
        fail "invalid $name subvolume"
      fi
    done
    if [[ -e "$top/$next_name" || -L "$top/$next_name" ]]; then
      if [[ -L "$top/$next_name" ]] || ! btrfs subvolume show "$top/$next_name" >/dev/null; then
        fail "unsafe staging subvolume"
      fi
      staging_contents=$(find "$top/$next_name" -mindepth 1 -print -quit) || fail "cannot inspect staging contents"
      [[ -z "$staging_contents" ]] || fail "staging subvolume is not empty"
    fi
    descendants=$(btrfs subvolume list -o "$top/$root_name") || fail "cannot inspect root descendants"
    while IFS= read -r line; do
      [[ -n "$line" ]] || continue
      [[ "$line" == *" path "* ]] || fail "unparseable root descendant"
      candidate=${line#* path }
      allowed=false
      for descendant in "${allowed_descendants[@]}"; do
        if [[ "$candidate" == "$root_name/$descendant" ]]; then allowed=true; break; fi
      done
      "$allowed" || fail "unexpected root descendant"
      nested=$(btrfs subvolume list -o "$top/$candidate") || fail "cannot inspect disposable descendants"
      [[ -z "$nested" ]] || fail "nested disposable subvolume"
    done <<< "$descendants"
    ;;
  *) fail "unknown check role" ;;
esac
